services:
  postgres:
    image: postgres:16
    container_name: monitorium_postgres
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - monitorium-postgres-data:/var/lib/postgresql/data
      - monitorium-postgres-logs:/var/log/postgresql
    networks:
      - monitorium

  frontend:
    container_name: monitorium_frontend
    restart: always
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.app
    env_file:
      - .env
    ports:
      - '${VITE_FRONTEND_PORT}:${NGINX_PORT}'
    networks:
      - monitorium
      
networks:
  monitorium:
    driver: bridge

volumes:
  monitorium-postgres-data:
  monitorium-postgres-logs: